spring:
  application:
    name: funtions
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/functions?&autoReconnect=true&characterEncoding=utf8
    username: root
    password: root
